name: Release Prep

on:
  workflow_dispatch:

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout next-release branch
        uses: actions/checkout@v4
        with:
          ref: next-release
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run standard-version (bump version, changelog, tag)
        run: npm run release

      - name: Push changes and tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push origin next-release
          git push origin --tags

      - name: Create PR from next-release to main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head next-release \
            --title "Release: $(jq -r .version package.json)" \
            --body "Automated release PR for version $(jq -r .version package.json)" \
          || echo "PR already exists or failed"
